### PR TITLE
ci: Added release script

### PR DESCRIPTION
**Pull request by Alexnortung**
Added release script, such that github actions can automatically publish the package to npm.

You do have set up a `NPM_TOKEN` in the secrets for your repo.

Then you can just use `npm run release` to publish a new version.

### CODE REVIEW

**Comment by uhyo** [comment]
Hi, thanks for contribution! I'd like to git it a try, so I prepared a `NPM_TOKEN`.

However there's a conflict with the other contribution from you 🥲 Could you resolve it? Otherwise LGTM.

**Comment by Alexnortung** [comment]
Alright, merge conflict solved :)

**Review by uhyo — APPROVED** [review]
Thanks! 🙂

**Comment by uhyo** [comment]
This worked perfectly, thank you 🙂 

https://github.com/uhyo/ts-array-length/releases/tag/v0.1.3

**Pull request merged**
