### PR TITLE
chore: Added cjs output

### PR DESCRIPTION
**Pull request by Alexnortung**
Output should also include commonjs

### CODE REVIEW

**Comment by uhyo** [comment]
Hi, thank you for your suggestion!

I am willing to provide a CJS output, but actually I'm not a fan of this double-tsconfig setup.

Can this be changed so that:

- Default is changed to CJS (remove `"type": "module"` in package.json)
- `index.mts` is added so that it still provides MJS endpoint

**Comment by Alexnortung** [comment]
Okay, I did remove the `type: module` from the package.json.
I didn't realize that it broke the esm build by removing `type: module`, but of course. I think the easiest way to fix it is by just putting a `package.json` file in `dist/esm` with the contents `{type: module}`. I think this is easier than having to use a bundler to make `.mjs` output.

Regarding the double tsconfig files, I think it makes sense to have two, but I can just move it to package.json if you want.

What do you think?

**Comment by uhyo** [comment]
I mean, there should be one build that provides both CJS and MJS. No `dist/esm` and `dist/cjs`.

The `"module": "node16"` setting in `tsconfig.json` is supposed to support having both in one build.

Please refer to another project of mine: https://github.com/uhyo/eslint-plugin-import-access/blob/bdbd05ae5aa39b81b419df50645f23264f660b63/package.json#L9-L11

Check how the `/flat-config` endpoint supports both CJS and MJS with one tsconfig.

**Comment by Alexnortung** [comment]
Okay, I did not know about `mts` and `cts` files, thanks :)
I have updated the branch now

**Review by uhyo — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
